import textwrap
from datetime import datetime
from reportlab.lib.pagesizes import LETTER
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from io import BytesIO

W, H = LETTER
ML = 55
MR = 55
TW = W - ML - MR

C_DARK    = colors.HexColor("#0f172a")
C_EMERALD = colors.HexColor("#059669")
C_GRAY    = colors.HexColor("#475569")
C_LIGHT   = colors.HexColor("#94a3b8")
C_BG      = colors.HexColor("#f0fdf4")
C_WHITE   = colors.white


def _wrap(text: str, max_chars: int) -> list:
    return textwrap.wrap(str(text).strip(), width=max(max_chars, 20)) or [""]


class ResumeBuilder:
    def __init__(self, buf):
        self.p = canvas.Canvas(buf, pagesize=LETTER)
        self.y = H - 125  # start below header

    def check_page(self, needed=50):
        if self.y < needed + 36:
            self.p.showPage()
            self.y = H - 50

    def section(self, title):
        self.y -= 10
        self.check_page(80)
        self.p.setFillColor(C_DARK)
        self.p.setFont("Helvetica-Bold", 10)
        self.p.drawString(ML, self.y, title.upper())
        self.y -= 5
        self.p.setStrokeColor(C_EMERALD)
        self.p.setLineWidth(1.5)
        self.p.line(ML, self.y, W - MR, self.y)
        self.p.setLineWidth(0.5)
        self.y -= 14

    def text(self, txt, indent=0, bold=False, color=None, size=9.5):
        if color is None:
            color = C_DARK
        font = "Helvetica-Bold" if bold else "Helvetica"
        self.p.setFont(font, size)
        self.p.setFillColor(color)
        for line in _wrap(txt, int((TW - indent) / 5.3)):
            self.check_page()
            self.p.drawString(ML + indent, self.y, line)
            self.y -= 13

    def bullet(self, txt):
        self.p.setFont("Helvetica", 9.5)
        self.p.setFillColor(C_DARK)
        lines = _wrap(txt, int((TW - 16) / 5.3))
        for i, line in enumerate(lines):
            self.check_page()
            if i == 0:
                self.p.setFillColor(C_EMERALD)
                self.p.circle(ML + 5, self.y + 3, 2, fill=1, stroke=0)
                self.p.setFillColor(C_DARK)
                self.p.drawString(ML + 14, self.y, line)
            else:
                self.p.drawString(ML + 14, self.y, line)
            self.y -= 13

    def footer(self, score):
        self.p.setFont("Helvetica", 7.5)
        self.p.setFillColor(C_LIGHT)
        self.p.drawCentredString(W / 2, 22,
            f"Generated by Baalebos Cloud AI  ·  {datetime.now().strftime('%B %d, %Y')}  ·  ATS Score: {score}%")


def generate_optimized_resume(filename: str, score: float, improvements: list,
                               resume_text: str = "", task_id: str = "",
                               structured: dict = None) -> BytesIO:
    buf = BytesIO()
    s = structured or {}

    name           = (s.get("name") or _first_line(resume_text) or "Candidate").strip()
    contact        = (s.get("contact") or _second_line(resume_text) or "").strip()
    summary        = (s.get("summary") or "").strip()
    experience     = s.get("experience") or []
    skills         = s.get("skills") or []
    education      = s.get("education") or []
    certifications = s.get("certifications") or []

    rb = ResumeBuilder(buf)
    p  = rb.p

    # ═══════════════════════════════════════════════════════════════════════
    # PAGE 1 — RESUME
    # ═══════════════════════════════════════════════════════════════════════

    # Header band
    p.setFillColor(C_DARK)
    p.rect(0, H - 110, W, 110, fill=1, stroke=0)

    # ATS badge
    badge_col = "#10b981" if score >= 80 else "#f59e0b" if score >= 60 else "#ef4444"
    p.setFillColor(colors.HexColor(badge_col))
    p.roundRect(W - MR - 90, H - 38, 90, 24, 6, fill=1, stroke=0)
    p.setFillColor(C_WHITE)
    p.setFont("Helvetica-Bold", 8)
    p.drawCentredString(W - MR - 45, H - 22, f"ATS SCORE  {score}%")

    # Name
    p.setFillColor(C_WHITE)
    p.setFont("Helvetica-Bold", 22)
    p.drawString(ML, H - 42, name.upper())

    # Contact
    if contact:
        p.setFont("Helvetica", 9)
        p.setFillColor(colors.HexColor("#94a3b8"))
        p.drawString(ML, H - 60, contact[:90])

    # Accent bar
    p.setFillColor(C_EMERALD)
    p.rect(ML, H - 72, 40, 3, fill=1, stroke=0)

    # Tagline
    p.setFont("Helvetica-Bold", 8)
    p.setFillColor(colors.HexColor("#6ee7b7"))
    p.drawString(ML, H - 88, "AI-OPTIMIZED RESUME  ·  BAALEBOS CLOUD  ·  INTERVIEW-READY")

    rb.y = H - 125

    # ── PROFESSIONAL SUMMARY ─────────────────────────────────────────────
    if summary:
        rb.section("Professional Summary")
        sum_lines = _wrap(summary, int(TW / 5.3))
        box_h = len(sum_lines) * 13 + 18
        p.setFillColor(C_BG)
        p.roundRect(ML, rb.y - box_h + 12, TW, box_h, 6, fill=1, stroke=0)
        p.setFont("Helvetica", 9.5)
        p.setFillColor(C_DARK)
        for line in sum_lines:
            rb.check_page()
            p.drawString(ML + 8, rb.y, line)
            rb.y -= 13
        rb.y -= 8

    # ── EXPERIENCE ───────────────────────────────────────────────────────
    if experience:
        rb.section("Work Experience")
        for job in experience:
            rb.check_page(needed=80)
            title_str   = (job.get("title") or "").strip()
            company_str = (job.get("company") or "").strip()
            dates_str   = (job.get("dates") or "").strip()
            bullets     = job.get("bullets") or []

            # Role title
            p.setFont("Helvetica-Bold", 10.5)
            p.setFillColor(C_DARK)
            p.drawString(ML, rb.y, title_str)
            if dates_str:
                p.setFont("Helvetica", 8.5)
                p.setFillColor(C_LIGHT)
                p.drawRightString(W - MR, rb.y, dates_str)
            rb.y -= 14

            # Company
            if company_str:
                p.setFont("Helvetica-Bold", 9)
                p.setFillColor(C_EMERALD)
                p.drawString(ML, rb.y, company_str)
                rb.y -= 14

            # Bullets
            for b in bullets:
                if b and b.strip():
                    rb.bullet(b.strip())
            rb.y -= 6

    # ── SKILLS ───────────────────────────────────────────────────────────
    if skills:
        rb.section("Technical Skills")
        x = ML
        row_y = rb.y
        for skill in skills:
            if not skill:
                continue
            sw = p.stringWidth(str(skill), "Helvetica", 9) + 18
            if x + sw > W - MR:
                x = ML
                row_y -= 22
            rb.check_page(30)
            p.setFillColor(colors.HexColor("#ecfdf5"))
            p.roundRect(x, row_y - 3, sw, 17, 4, fill=1, stroke=0)
            p.setFillColor(C_EMERALD)
            p.setFont("Helvetica-Bold", 9)
            p.drawString(x + 8, row_y + 5, str(skill))
            x += sw + 6
        rb.y = row_y - 24

    # ── EDUCATION ────────────────────────────────────────────────────────
    if education:
        rb.section("Education")
        for edu in education:
            rb.check_page(40)
            degree = (edu.get("degree") or "").strip()
            school = (edu.get("school") or "").strip()
            year   = (edu.get("year") or "").strip()
            p.setFont("Helvetica-Bold", 9.5)
            p.setFillColor(C_DARK)
            p.drawString(ML, rb.y, degree)
            if year:
                p.setFont("Helvetica", 8.5)
                p.setFillColor(C_LIGHT)
                p.drawRightString(W - MR, rb.y, year)
            rb.y -= 13
            if school:
                p.setFont("Helvetica", 9)
                p.setFillColor(C_GRAY)
                p.drawString(ML, rb.y, school)
                rb.y -= 14

    # ── CERTIFICATIONS ───────────────────────────────────────────────────
    if certifications:
        rb.section("Certifications")
        for cert in certifications:
            if cert and cert.strip():
                rb.bullet(cert.strip())

    rb.footer(score)

    # ═══════════════════════════════════════════════════════════════════════
    # PAGE 2 — AI IMPROVEMENT REPORT
    # ═══════════════════════════════════════════════════════════════════════
    p.showPage()

    # Header
    p.setFillColor(C_DARK)
    p.rect(0, H - 70, W, 70, fill=1, stroke=0)
    p.setFillColor(C_WHITE)
    p.setFont("Helvetica-Bold", 16)
    p.drawString(ML, H - 32, "Baalebos AI — Optimization Report")
    p.setFont("Helvetica", 9)
    p.setFillColor(colors.HexColor("#94a3b8"))
    p.drawString(ML, H - 52,
        f"ATS Score: {score}%  ·  Target: 90%+  ·  {len(improvements)} suggestion(s)  ·  {datetime.now().strftime('%B %d, %Y')}")

    y2 = H - 90

    # Score bar
    p.setFont("Helvetica-Bold", 10)
    p.setFillColor(C_DARK)
    p.drawString(ML, y2, f"Current Score: {score}%")
    p.setFont("Helvetica", 9)
    p.setFillColor(C_LIGHT)
    p.drawRightString(W - MR, y2, "Target: 90%+")
    y2 -= 16

    p.setFillColor(colors.HexColor("#e2e8f0"))
    p.rect(ML, y2, TW, 10, fill=1, stroke=0)
    bar_col = "#10b981" if score >= 80 else "#f59e0b" if score >= 60 else "#ef4444"
    p.setFillColor(colors.HexColor(bar_col))
    p.rect(ML, y2, TW * min(score / 100, 1), 10, fill=1, stroke=0)
    tx = ML + TW * 0.9
    p.setStrokeColor(C_EMERALD)
    p.setLineWidth(2)
    p.line(tx, y2 - 3, tx, y2 + 14)
    p.setFont("Helvetica-Bold", 7)
    p.setFillColor(C_EMERALD)
    p.drawCentredString(tx, y2 + 17, "90%")
    y2 -= 32

    # Suggestions heading
    p.setFont("Helvetica-Bold", 11)
    p.setFillColor(C_DARK)
    p.drawString(ML, y2, "AI-Powered Suggestions to Reach 90%+")
    y2 -= 6
    p.setStrokeColor(C_EMERALD)
    p.setLineWidth(1.5)
    p.line(ML, y2, W - MR, y2)
    p.setLineWidth(0.5)
    y2 -= 18

    for item in improvements:
        if y2 < 60:
            p.showPage()
            y2 = H - 50

        skill = (item.get("skill") or "Tip").strip()
        text  = (item.get("bullet_point") or "").strip()

        bw = min(p.stringWidth(skill.upper(), "Helvetica-Bold", 8) + 22, 220)
        p.setFillColor(colors.HexColor("#ecfdf5"))
        p.roundRect(ML, y2 - 3, bw, 18, 4, fill=1, stroke=0)
        p.setFillColor(C_EMERALD)
        p.setFont("Helvetica-Bold", 8)
        p.drawString(ML + 8, y2 + 6, skill.upper()[:32])
        y2 -= 22

        p.setFillColor(C_DARK)
        p.setFont("Helvetica", 9.5)
        for line in _wrap(text, int(TW / 5.3)):
            if y2 < 50:
                p.showPage()
                y2 = H - 50
            p.drawString(ML + 10, y2, f"• {line}")
            y2 -= 13
        y2 -= 8

    p.setFont("Helvetica", 7.5)
    p.setFillColor(C_LIGHT)
    p.drawCentredString(W / 2, 22,
        "Generated by Baalebos Cloud AI  ·  baalebo.xyz  ·  Interview-ready resume")

    p.save()
    buf.seek(0)
    return buf


def _first_line(text: str) -> str:
    for line in (text or "").split("\n"):
        if line.strip():
            return line.strip()
    return "Candidate"


def _second_line(text: str) -> str:
    found = 0
    for line in (text or "").split("\n"):
        if line.strip():
            found += 1
            if found == 2:
                return line.strip()
    return ""
