import textwrap
from reportlab.lib.pagesizes import LETTER
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from io import BytesIO


def _draw_header(p, width, height, title, subtitle):
    p.setFillColor(colors.HexColor("#0f172a"))
    p.rect(0, height - 72, width, 72, fill=1, stroke=0)
    p.setFillColor(colors.white)
    p.setFont("Helvetica-Bold", 18)
    p.drawString(36, height - 38, title)
    p.setFont("Helvetica", 9)
    p.drawString(36, height - 54, subtitle)


def _draw_footer(p, width, page_num):
    p.setFont("Helvetica", 8)
    p.setFillColor(colors.HexColor("#94a3b8"))
    p.drawCentredString(width / 2, 24, f"Generated by Baalebos Cloud AI  •  Page {page_num}")


def _wrapped_lines(text: str, max_chars: int) -> list:
    """Wrap a long string into lines of max_chars."""
    return textwrap.wrap(text, width=max_chars) or [""]


def generate_optimized_resume(filename: str, score: float, improvements: list,
                               resume_text: str = "", task_id: str = "") -> BytesIO:
    """
    Page 1 — Full original resume content (extracted text, properly wrapped).
    Page 2 — ATS score + AI improvement suggestions.
    """
    buffer = BytesIO()
    p = canvas.Canvas(buffer, pagesize=LETTER)
    width, height = LETTER
    margin = 36
    line_height = 13
    text_width = width - margin * 2

    # ── PAGE 1: Full Resume ───────────────────────────────────────────────────
    _draw_header(p, width, height,
                 "Baalebos AI — Your Resume",
                 f"File: {filename}  •  ATS Match Score: {score}%")

    y = height - 90
    p.setFont("Helvetica", 9)
    p.setFillColor(colors.HexColor("#1e293b"))

    if resume_text:
        for paragraph in resume_text.split("\n"):
            paragraph = paragraph.strip()
            if not paragraph:
                y -= 6  # blank line gap
                continue
            lines = _wrapped_lines(paragraph, max_chars=int(text_width / 5.2))
            for line in lines:
                if y < margin + 30:
                    _draw_footer(p, width, 1)
                    p.showPage()
                    _draw_header(p, width, height,
                                 "Baalebos AI — Your Resume (cont.)",
                                 f"File: {filename}")
                    y = height - 90
                    p.setFont("Helvetica", 9)
                    p.setFillColor(colors.HexColor("#1e293b"))
                p.drawString(margin, y, line)
                y -= line_height
    else:
        p.drawString(margin, y, "Resume text could not be extracted. Please use a text-based PDF.")

    _draw_footer(p, width, 1)

    # ── PAGE 2: AI Improvements ───────────────────────────────────────────────
    p.showPage()
    _draw_header(p, width, height,
                 "Baalebos AI — Optimization Report",
                 f"ATS Match Score: {score}%  •  {len(improvements)} improvement(s) identified")

    y = height - 100

    # Score bar
    p.setFont("Helvetica-Bold", 11)
    p.setFillColor(colors.HexColor("#0f172a"))
    p.drawString(margin, y, f"Overall ATS Score: {score}%")
    y -= 18

    bar_w = text_width
    p.setFillColor(colors.HexColor("#e2e8f0"))
    p.rect(margin, y, bar_w, 10, fill=1, stroke=0)
    fill_color = "#10b981" if score >= 80 else "#f59e0b" if score >= 60 else "#ef4444"
    p.setFillColor(colors.HexColor(fill_color))
    p.rect(margin, y, bar_w * (score / 100), 10, fill=1, stroke=0)
    y -= 28

    # Section title
    p.setFont("Helvetica-Bold", 12)
    p.setFillColor(colors.HexColor("#0f172a"))
    p.drawString(margin, y, "AI-Powered Improvement Suggestions")
    y -= 6
    p.setStrokeColor(colors.HexColor("#e2e8f0"))
    p.line(margin, y, width - margin, y)
    y -= 18

    for i, item in enumerate(improvements):
        if y < margin + 50:
            _draw_footer(p, width, 2)
            p.showPage()
            _draw_header(p, width, height, "Baalebos AI — Improvements (cont.)", "")
            y = height - 90
            p.setFont("Helvetica-Bold", 12)

        skill = item.get("skill", "Tip")
        bullet = item.get("bullet_point", "")

        # Skill badge
        badge_w = min(len(skill) * 6.5 + 16, 180)
        p.setFillColor(colors.HexColor("#ecfdf5"))
        p.roundRect(margin, y - 4, badge_w, 16, 4, fill=1, stroke=0)
        p.setFillColor(colors.HexColor("#059669"))
        p.setFont("Helvetica-Bold", 8)
        p.drawString(margin + 6, y + 4, skill.upper()[:28])

        y -= 20

        # Bullet text wrapped
        p.setFillColor(colors.HexColor("#334155"))
        p.setFont("Helvetica", 9)
        for line in _wrapped_lines(bullet, max_chars=int(text_width / 5.0)):
            if y < margin + 30:
                break
            p.drawString(margin + 10, y, f"• {line}")
            y -= line_height

        y -= 8  # gap between items

    _draw_footer(p, width, 2)
    p.save()
    buffer.seek(0)
    return buffer
