from reportlab.lib.pagesizes import LETTER
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from io import BytesIO

def generate_optimized_resume(filename, score, improvements):
    """
    Creates a professional PDF report showing the original resume 
    plus the AI-suggested improvements.
    """
    buffer = BytesIO()
    p = canvas.Canvas(buffer, pagesize=LETTER)
    width, height = LETTER

    # --- Header: Baalebos Cloud Branding ---
    p.setFillColor(colors.HexColor("#0f172a")) # Dark Slate
    p.rect(0, height - 80, width, 80, fill=1)
    
    p.setFillColor(colors.white)
    p.setFont("Helvetica-Bold", 22)
    p.drawString(40, height - 45, "Baalebos AI Optimization Report")
    
    p.setFont("Helvetica", 10)
    p.drawString(40, height - 60, f"Analysis for: {filename} • Match Score: {score}%")

    # --- Section: AI Suggested Improvements ---
    p.setFillColor(colors.black)
    p.setFont("Helvetica-Bold", 14)
    p.drawString(40, height - 120, "✨ AI-Powered Bullet Point Suggestions")
    
    p.setStrokeColor(colors.HexColor("#e2e8f0"))
    p.line(40, height - 130, width - 40, height - 130)

    y_position = height - 160
    p.setFont("Helvetica", 11)

    # Loop through the improvements (from our optimizer logic)
    for item in improvements[:8]: # Limit to top 8 to stay on one page
        if y_position < 100: break # Simple page overflow check
        
        # Skill Badge
        p.setFillColor(colors.HexColor("#ecfdf5")) # Light Emerald
        p.rect(40, y_position - 5, 100, 18, fill=1, stroke=0)
        
        p.setFillColor(colors.HexColor("#059669")) # Dark Emerald
        p.setFont("Helvetica-Bold", 9)
        p.drawString(45, y_position, f"FIX: {item['skill'].upper()}")
        
        # The Bullet Point
        p.setFillColor(colors.black)
        p.setFont("Helvetica-Oblique", 10)
        p.drawString(150, y_position, f"\"{item['bullet_point']}\"")
        
        y_position -= 40

    # --- Footer ---
    p.setFont("Helvetica-Bold", 10)
    p.setFillColor(colors.HexColor("#64748b"))
    p.drawCentredString(width/2, 40, "Generated by Baalebos Cloud AI • global-tech-ready")

    p.showPage()
    p.save()

    buffer.seek(0)
    return buffer
