import {useState} from 'react';
import axios from 'axios';
const API=import.meta.env.VITE_API_URL||'http://localhost:8000/api/v1';
const labels={external_started:'Complete on employer website',submitted_external:'Submitted — confirmed by you',submitted_internal:'Received on Baalebos',applied:'Legacy record — receipt unconfirmed',pending:'Pending',processed:'Prepared',reviewed:'Reviewed',interview:'Interview',offer:'Offer',rejected:'Not selected'};
export default function ApplicationsTable({applications=[],onDelete,token}){
 const [updates,setUpdates]=useState({});const [error,setError]=useState('');const [busy,setBusy]=useState(null);
 const confirm=async app=>{setBusy(app.id);setError('');try{await axios.patch(`${API}/jobs/${app.job_id}/application-status`,null,{params:{new_status:'submitted_external'},headers:{Authorization:`Bearer ${token}`}});setUpdates(v=>({...v,[app.id]:'submitted_external'}))}catch{setError('Could not update your application. Please retry.')}finally{setBusy(null)}};
 return <div className="space-y-4">{error&&<p role="alert" className="text-red-700">{error}</p>}{!applications.length&&<div className="bg-white rounded-2xl border border-dashed border-slate-200 p-9 text-center"><p className="font-medium">No tracked applications yet</p><p className="text-sm text-slate-500 mt-2">Find a role and prepare your application.</p><a href="/jobs" className="inline-block text-emerald-700 mt-4">Explore jobs →</a></div>}{applications.map(app=>{const status=updates[app.id]||app.status;return <article key={app.id} className="bg-white rounded-2xl border border-slate-200 p-6"><div className="flex flex-wrap justify-between gap-3"><p className="text-xs text-slate-500">Tracked {new Date(app.created_at).toLocaleDateString()}</p><span className="text-xs font-medium rounded-lg px-3 py-1 bg-slate-100">{labels[status]||status}</span></div><h3 className="font-semibold mt-3 text-lg">{app.job?.title||'Vacancy unavailable'}</h3><p className="text-slate-500 text-sm mt-1">{app.job?.company} · {app.job?.location||'Location not provided'}</p><p className="text-sm text-slate-500 mt-3">{app.ats_score!=null?`Documented requirement coverage: ${app.ats_score}%`:'No assessment for this vacancy'}</p><div className="flex flex-wrap gap-4 mt-5 text-sm">{app.job?.url&&<a className="text-emerald-700" href={app.job.url} target="_blank" rel="noopener noreferrer">Employer application ↗</a>}{status==='external_started'&&<button disabled={busy===app.id} className="text-emerald-700" onClick={()=>confirm(app)}>I completed the employer application</button>}{onDelete&&<button className="text-slate-500 ml-auto" onClick={()=>onDelete(app.id)}>Remove from tracker</button>}</div></article>})}</div>
}
