import {useState,useEffect} from 'react';
import axios from 'axios';
import {X,MapPin,Briefcase,ExternalLink} from 'lucide-react';
const API=import.meta.env.VITE_API_URL||'http://localhost:8000/api/v1';
const knownSkills=['Python','Docker','Kubernetes','Terraform','Ansible','Azure','AWS','Git','Jenkins','SQL','React','Linux','PowerShell'];
export default function JobFeed({jobs=[],onApply,lastTaskId}){
 const [job,setJob]=useState(null);const [busy,setBusy]=useState(false);const [result,setResult]=useState(null);const [error,setError]=useState('');const [attach,setAttach]=useState(false);
 useEffect(()=>{if(!job)return;const close=e=>{if(e.key==='Escape')setJob(null)};window.addEventListener('keydown',close);const previous=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{window.removeEventListener('keydown',close);document.body.style.overflow=previous}},[job]);
 const select=j=>{setJob(j);setResult(null);setError('');setAttach(false)};
 const apply=async()=>{setBusy(true);setError('');try{setResult(await onApply(job.id,job.url,attach?lastTaskId:null))}catch(e){setError(e.response?.data?.detail||'Could not prepare your application. Please retry.')}finally{setBusy(false)}};
 const skills=j=>knownSkills.filter(s=>new RegExp(`\\b${s}\\b`,'i').test(j.description||''));
 return <><div className="grid md:grid-cols-2 gap-5">{jobs.map(j=><article key={j.id} className="bg-white border border-slate-200 rounded-2xl p-6 hover:border-emerald-300 transition-colors"><div className="flex justify-between gap-3"><p className="text-sm text-slate-500">{j.company||'Company not provided'}</p><span className="text-xs rounded-lg px-2 py-1 bg-slate-100">{j.work_type||'Work arrangement unknown'}</span></div><h2 className="text-lg font-semibold mt-3">{j.title}</h2><p className="flex gap-2 items-center text-sm text-slate-500 mt-3"><MapPin size={15}/>{j.location||'Location not provided'}</p><p className="text-sm text-slate-500 mt-2">{j.salary_range||'Compensation not disclosed'}</p><div className="flex flex-wrap gap-2 mt-4">{skills(j).slice(0,5).map(s=><span key={s} className="text-xs border border-slate-200 rounded-lg px-3 py-2">{s}</span>)}</div><p className="text-sm text-slate-500 line-clamp-2 mt-4">{j.description}</p><button className="mt-5 text-emerald-800 font-medium text-sm" onClick={()=>select(j)}>View role and apply →</button></article>)}</div>{!jobs.length&&<div className="bg-white border border-dashed border-slate-200 rounded-2xl p-10 text-center text-slate-500">No opportunities found. Try another filter.</div>}
 {job&&<div className="fixed inset-0 z-50 bg-black/40 flex items-center justify-center p-4" onClick={()=>setJob(null)}><section role="dialog" aria-modal="true" aria-labelledby="job-title" className="bg-white rounded-2xl w-full max-w-3xl max-h-[90vh] overflow-y-auto p-6 md:p-8" onClick={e=>e.stopPropagation()}><div className="flex justify-between gap-5"><div><p className="text-emerald-700 text-sm">{job.company}</p><h2 id="job-title" className="text-2xl font-semibold mt-1">{job.title}</h2></div><button autoFocus aria-label="Close job details" onClick={()=>setJob(null)}><X/></button></div><div className="flex flex-wrap gap-3 my-5 text-sm text-slate-500"><span>{job.location||'Location not provided'}</span><span>{job.work_type||'Unknown work arrangement'}</span><span>{job.salary_range||'Compensation not disclosed'}</span><span>Source: {job.source||'Employer'}</span></div>
 <h3 className="font-semibold border-b border-slate-100 pb-3">Role description and requirements</h3><div className="text-slate-700 text-sm leading-7 whitespace-pre-wrap my-5">{job.description||'Full description not provided. Check the original posting.'}</div><p className="bg-slate-50 rounded-xl p-4 text-sm text-slate-500">Check location restrictions, work authorization, and required qualifications in the original posting before applying.</p>
 {error&&<p role="alert" className="text-red-700 bg-red-50 p-4 rounded-xl mt-4">{error}</p>}
 {result?<div className="mt-6 border border-emerald-200 bg-emerald-50 p-5 rounded-xl"><h3 className="font-semibold">{result.status==='submitted_internal'?'Received on Baalebos':'Application tracked'}</h3><p className="text-sm mt-2">{result.message}</p>{result.job_url&&<a href={result.job_url} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 bg-emerald-700 text-white rounded-xl px-5 py-3 mt-4">Complete on employer website <ExternalLink size={16}/></a>}</div>:<div className="mt-6 space-y-4"><a href={`/optimizer?job=${job.id}`} className="text-emerald-800 font-medium text-sm inline-flex gap-2 items-center"><Briefcase size={16}/>Tailor a resume to this role →</a>{lastTaskId&&<label className="flex gap-3 items-center text-sm"><input type="checkbox" checked={attach} onChange={e=>setAttach(e.target.checked)}/>Attach my latest resume (must match this description)</label>}<div className="flex gap-3 flex-wrap"><button disabled={busy} onClick={apply} className="bg-emerald-700 text-white px-5 py-3 rounded-xl font-medium disabled:opacity-50">{busy?'Preparing…':job.url?'Track and continue to employer':'Submit to employer on Baalebos'}</button>{job.url&&<a href={job.url} target="_blank" rel="noopener noreferrer" className="border border-slate-200 rounded-xl px-4 py-3 text-sm">View original ↗</a>}</div></div>}</section></div>}</>
}
